//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLG2007.WebParts.MyPlanner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLG2007.WebParts.MyPlanner.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Required.
        /// </summary>
        internal static string ApprovalRequired {
            get {
                return ResourceManager.GetString("ApprovalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        internal static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find the Calendar Store list.
        /// </summary>
        internal static string CalendarStoreIsMissing {
            get {
                return ResourceManager.GetString("CalendarStoreIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string CalendarStoreRole {
            get {
                return ResourceManager.GetString("CalendarStoreRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string CalendarStoreRoleDesc {
            get {
                return ResourceManager.GetString("CalendarStoreRoleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planner Store Settings.
        /// </summary>
        internal static string CalendarStoreSettings {
            get {
                return ResourceManager.GetString("CalendarStoreSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Store URL.
        /// </summary>
        internal static string CalendarStoreURL {
            get {
                return ResourceManager.GetString("CalendarStoreURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL of the Calendar Store.
        /// </summary>
        internal static string CalendarStoreUrlDesc {
            get {
                return ResourceManager.GetString("CalendarStoreUrlDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyPlanner is complaint with site theam.
        /// </summary>
        internal static string CalendarTheamComplaint {
            get {
                return ResourceManager.GetString("CalendarTheamComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string CatAdvanced {
            get {
                return ResourceManager.GetString("CatAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Server Settings.
        /// </summary>
        internal static string CatClassServer {
            get {
                return ResourceManager.GetString("CatClassServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Settings.
        /// </summary>
        internal static string CatExchange {
            get {
                return ResourceManager.GetString("CatExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Settings.
        /// </summary>
        internal static string CatSharePoint {
            get {
                return ResourceManager.GetString("CatSharePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification Obtained.
        /// </summary>
        internal static string CertificationObtained {
            get {
                return ResourceManager.GetString("CertificationObtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string chgHeaderButton {
            get {
                return ResourceManager.GetString("chgHeaderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Site Header:.
        /// </summary>
        internal static string chgHeaderLB1 {
            get {
                return ResourceManager.GetString("chgHeaderLB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to a custom header page relative to the /_layouts/1033 directory. eg.  LPUtilities/LPHeader.aspx.
        /// </summary>
        internal static string chgHeaderLB2 {
            get {
                return ResourceManager.GetString("chgHeaderLB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course ID.
        /// </summary>
        internal static string CourseID {
            get {
                return ResourceManager.GetString("CourseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course URL.
        /// </summary>
        internal static string CourseURL {
            get {
                return ResourceManager.GetString("CourseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        internal static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Server Student URL e.g. http://myserver/MicrosoftClassServer/Student.
        /// </summary>
        internal static string CSURLDesc {
            get {
                return ResourceManager.GetString("CSURLDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Server Student URL.
        /// </summary>
        internal static string CSURLName {
            get {
                return ResourceManager.GetString("CSURLName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Server Web Service e.g. http://myserver/MicrosoftClassServer/Service.
        /// </summary>
        internal static string CSWSDesc {
            get {
                return ResourceManager.GetString("CSWSDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Server Web Service.
        /// </summary>
        internal static string CSWSName {
            get {
                return ResourceManager.GetString("CSWSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Name.
        /// </summary>
        internal static string DNSName {
            get {
                return ResourceManager.GetString("DNSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS Name.
        /// </summary>
        internal static string DNSNameDesc {
            get {
                return ResourceManager.GetString("DNSNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS Name is missing.
        /// </summary>
        internal static string DNSNameIsMissing {
            get {
                return ResourceManager.GetString("DNSNameIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this to enable using a domain other than the users default domain.
        /// </summary>
        internal static string EnableOverrideDomainDesc {
            get {
                return ResourceManager.GetString("EnableOverrideDomainDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override default mail alias.
        /// </summary>
        internal static string EnableOverrideDomainText {
            get {
                return ResourceManager.GetString("EnableOverrideDomainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll.
        /// </summary>
        internal static string Enrol {
            get {
                return ResourceManager.GetString("Enrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: .
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSSApointment Style Sheet not found.
        /// </summary>
        internal static string ErrorParsingCssAppointmentSS {
            get {
                return ResourceManager.GetString("ErrorParsingCssAppointmentSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSSClass Style Sheet not found.
        /// </summary>
        internal static string ErrorParsingCssClassSS {
            get {
                return ResourceManager.GetString("ErrorParsingCssClassSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSSHeadClass Style Sheet not found.
        /// </summary>
        internal static string ErrorParsingCssShowMoreClass {
            get {
                return ResourceManager.GetString("ErrorParsingCssShowMoreClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Class Server&apos;s teacher client URL not found.
        /// </summary>
        internal static string ErrorParsingCSTeacherClientURL {
            get {
                return ResourceManager.GetString("ErrorParsingCSTeacherClientURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Server URL not found.
        /// </summary>
        internal static string ErrorParsingCSURL {
            get {
                return ResourceManager.GetString("ErrorParsingCSURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date not found.
        /// </summary>
        internal static string ErrorParsingDate {
            get {
                return ResourceManager.GetString("ErrorParsingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain name not found.
        /// </summary>
        internal static string ErrorParsingDomain {
            get {
                return ResourceManager.GetString("ErrorParsingDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to detect whether or not to override default mail alias.
        /// </summary>
        internal static string ErrorParsingEnableOverrideDomain {
            get {
                return ResourceManager.GetString("ErrorParsingEnableOverrideDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange URL not found.
        /// </summary>
        internal static string ErrorParsingExURL {
            get {
                return ResourceManager.GetString("ErrorParsingExURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links group not found.
        /// </summary>
        internal static string ErrorParsingQuickLinksGroup {
            get {
                return ResourceManager.GetString("ErrorParsingQuickLinksGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Link WS URL not found.
        /// </summary>
        internal static string ErrorParsingQuickLinkWSURL {
            get {
                return ResourceManager.GetString("ErrorParsingQuickLinkWSURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show errors  not found.
        /// </summary>
        internal static string ErrorParsingShowErrors {
            get {
                return ResourceManager.GetString("ErrorParsingShowErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint lists titles not found.
        /// </summary>
        internal static string ErrorParsingSPSListsTitles {
            get {
                return ResourceManager.GetString("ErrorParsingSPSListsTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint lists URLs not found.
        /// </summary>
        internal static string ErrorParsingSPSListsURL {
            get {
                return ResourceManager.GetString("ErrorParsingSPSListsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID not found.
        /// </summary>
        internal static string ErrorParsingUserID {
            get {
                return ResourceManager.GetString("ErrorParsingUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string EventsPageTitle {
            get {
                return ResourceManager.GetString("EventsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Domain e.g. Demo.
        /// </summary>
        internal static string EXDomDesc {
            get {
                return ResourceManager.GetString("EXDomDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Domain.
        /// </summary>
        internal static string EXDomName {
            get {
                return ResourceManager.GetString("EXDomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Outcomes.
        /// </summary>
        internal static string ExpectedOutcomes {
            get {
                return ResourceManager.GetString("ExpectedOutcomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires.
        /// </summary>
        internal static string Expires {
            get {
                return ResourceManager.GetString("Expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Admin Password.
        /// </summary>
        internal static string EXPwdDesc {
            get {
                return ResourceManager.GetString("EXPwdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Password.
        /// </summary>
        internal static string EXPwdName {
            get {
                return ResourceManager.GetString("EXPwdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange URL e.g. http://myserver/exchange.
        /// </summary>
        internal static string EXURLDesc {
            get {
                return ResourceManager.GetString("EXURLDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange URL.
        /// </summary>
        internal static string EXURLName {
            get {
                return ResourceManager.GetString("EXURLName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Admin User.
        /// </summary>
        internal static string EXUserDesc {
            get {
                return ResourceManager.GetString("EXUserDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange User.
        /// </summary>
        internal static string EXUserName {
            get {
                return ResourceManager.GetString("EXUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Mode.
        /// </summary>
        internal static string IsParentMode {
            get {
                return ResourceManager.GetString("IsParentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Parent Mode.
        /// </summary>
        internal static string IsParentModeDesc {
            get {
                return ResourceManager.GetString("IsParentModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified at.
        /// </summary>
        internal static string LastModifiedAt {
            get {
                return ResourceManager.GetString("LastModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Area.
        /// </summary>
        internal static string LearningArea {
            get {
                return ResourceManager.GetString("LearningArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma separated list of Event List Titles matching the event lists specified above e.g.School Events,Department Events .
        /// </summary>
        internal static string LITDesc {
            get {
                return ResourceManager.GetString("LITDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event List Title(s).
        /// </summary>
        internal static string LITName {
            get {
                return ResourceManager.GetString("LITName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string NewSiteGoBtn {
            get {
                return ResourceManager.GetString("NewSiteGoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for your new team site and click go to create the site..
        /// </summary>
        internal static string NewSiteInstr {
            get {
                return ResourceManager.GetString("NewSiteInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Site Description:.
        /// </summary>
        internal static string NewSiteLBDescription {
            get {
                return ResourceManager.GetString("NewSiteLBDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Site Name:.
        /// </summary>
        internal static string NewSiteLBName {
            get {
                return ResourceManager.GetString("NewSiteLBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Site.
        /// </summary>
        internal static string NewSiteTitle {
            get {
                return ResourceManager.GetString("NewSiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string NewsPageTitle {
            get {
                return ResourceManager.GetString("NewsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Unable to display Class Server data.
        /// </summary>
        internal static string NoCS {
            get {
                return ResourceManager.GetString("NoCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Unable to display Exchange data..
        /// </summary>
        internal static string NoEX {
            get {
                return ResourceManager.GetString("NoEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Unable to display SharePoint data..
        /// </summary>
        internal static string NoSPS {
            get {
                return ResourceManager.GetString("NoSPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Development.
        /// </summary>
        internal static string PDPageTitle {
            get {
                return ResourceManager.GetString("PDPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all required properties have been configured..
        /// </summary>
        internal static string PropNotSet {
            get {
                return ResourceManager.GetString("PropNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a generic user account when using Integrated security.
        /// </summary>
        internal static string PWDesc {
            get {
                return ResourceManager.GetString("PWDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Password.
        /// </summary>
        internal static string PWName {
            get {
                return ResourceManager.GetString("PWName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of the Quick Links web service.
        /// </summary>
        internal static string QLWSDesc {
            get {
                return ResourceManager.GetString("QLWSDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links Web Service URL.
        /// </summary>
        internal static string QLWSName {
            get {
                return ResourceManager.GetString("QLWSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {0} doesn&apos;t exist or Calendar Store URL {1}  is incorrect.
        /// </summary>
        internal static string RoleMissing {
            get {
                return ResourceManager.GetString("RoleMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows errors from the different data sources.
        /// </summary>
        internal static string ShowErrDesc {
            get {
                return ResourceManager.GetString("ShowErrDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Errors.
        /// </summary>
        internal static string ShowErrName {
            get {
                return ResourceManager.GetString("ShowErrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma separated list of Event List URLs e.g. http://myserver/schools/AmstelPS/Lists/Events,http://myserver/C2/MySchedules/Lists/Events.
        /// </summary>
        internal static string SPEventListDesc {
            get {
                return ResourceManager.GetString("SPEventListDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event List URL(s).
        /// </summary>
        internal static string SPEventListName {
            get {
                return ResourceManager.GetString("SPEventListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A group name in the Quick Links on My Site to search for Appointment Items. If not specified, all groups will be searched.
        /// </summary>
        internal static string SPQlinkDesc {
            get {
                return ResourceManager.GetString("SPQlinkDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) Quick Links Group.
        /// </summary>
        internal static string SPQlinkName {
            get {
                return ResourceManager.GetString("SPQlinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a generic user account when using Integrated security.
        /// </summary>
        internal static string UNDesc {
            get {
                return ResourceManager.GetString("UNDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Username.
        /// </summary>
        internal static string UNName {
            get {
                return ResourceManager.GetString("UNName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL of the User Preferences Store.
        /// </summary>
        internal static string UserPreferencesStoreDesc {
            get {
                return ResourceManager.GetString("UserPreferencesStoreDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Preferences Store {0}  is missing or inaccessible.
        /// </summary>
        internal static string UserPreferencesStoreMissing {
            get {
                return ResourceManager.GetString("UserPreferencesStoreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Preferences Store URL.
        /// </summary>
        internal static string UserPreferencesStoreUrl {
            get {
                return ResourceManager.GetString("UserPreferencesStoreUrl", resourceCulture);
            }
        }
    }
}
