//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLG2007.WebParts.MyChildren {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLG2007.WebParts.MyChildren.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This propery specifies the Active Directory attribute that the web part uses to get the current logged on children..
        /// </summary>
        internal static string ADChildAttributeDesc {
            get {
                return ResourceManager.GetString("ADChildAttributeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory Child Attribute.
        /// </summary>
        internal static string ADChildAttributeName {
            get {
                return ResourceManager.GetString("ADChildAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property specifies the LDAP Entry point on active directory to search for parents and children information..
        /// </summary>
        internal static string ADEntryPointDesc {
            get {
                return ResourceManager.GetString("ADEntryPointDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory Entry Point.
        /// </summary>
        internal static string ADEntryPointName {
            get {
                return ResourceManager.GetString("ADEntryPointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory Settings.
        /// </summary>
        internal static string ADSettingsCategory {
            get {
                return ResourceManager.GetString("ADSettingsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        internal static string Assignments {
            get {
                return ResourceManager.GetString("Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One child or more does not exist.
        /// </summary>
        internal static string ChildDontExist {
            get {
                return ResourceManager.GetString("ChildDontExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL of picture appears if child has no picture.
        /// </summary>
        internal static string DefaultPictureDesc {
            get {
                return ResourceManager.GetString("DefaultPictureDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default picture URL.
        /// </summary>
        internal static string DefaultPictureURL {
            get {
                return ResourceManager.GetString("DefaultPictureURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving child {0} information and returned while the following error message {1}.
        /// </summary>
        internal static string ErrorRetrievingChildInfo {
            get {
                return ResourceManager.GetString("ErrorRetrievingChildInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occcured while retrieving user&apos;s children and returned with message {0}.
        /// </summary>
        internal static string ErrorRetrievingChildren {
            get {
                return ResourceManager.GetString("ErrorRetrievingChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred:.
        /// </summary>
        internal static string GenericErr {
            get {
                return ResourceManager.GetString("GenericErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid students&apos; site URL.
        /// </summary>
        internal static string InvalidStudentURL {
            get {
                return ResourceManager.GetString("InvalidStudentURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading {0} picture.
        /// </summary>
        internal static string LoadPicErr {
            get {
                return ResourceManager.GetString("LoadPicErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Settings.
        /// </summary>
        internal static string MiscSettingsCategory {
            get {
                return ResourceManager.GetString("MiscSettingsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string Nexttext {
            get {
                return ResourceManager.GetString("Nexttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No children available in this school..
        /// </summary>
        internal static string NoChild {
            get {
                return ResourceManager.GetString("NoChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not found child with username {0}.  Please contact your system administrator..
        /// </summary>
        internal static string NoChildFound {
            get {
                return ResourceManager.GetString("NoChildFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of children per page.
        /// </summary>
        internal static string PageSizeDesc {
            get {
                return ResourceManager.GetString("PageSizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of children per page.
        /// </summary>
        internal static string PageSizeTitle {
            get {
                return ResourceManager.GetString("PageSizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the title of the picture library that holds the students&apos; images..
        /// </summary>
        internal static string PictureLibraryTitleDesc {
            get {
                return ResourceManager.GetString("PictureLibraryTitleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children&apos;s Images Picture Library title.
        /// </summary>
        internal static string PictureLibraryTitleName {
            get {
                return ResourceManager.GetString("PictureLibraryTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the url of the picture library that holds the students&apos; images..
        /// </summary>
        internal static string PictureLibraryUrlDesc {
            get {
                return ResourceManager.GetString("PictureLibraryUrlDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children&apos;s Images Picture Library URL.
        /// </summary>
        internal static string PictureLibraryUrlName {
            get {
                return ResourceManager.GetString("PictureLibraryUrlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children pictures&apos; settings.
        /// </summary>
        internal static string PicturesSettingsCategory {
            get {
                return ResourceManager.GetString("PicturesSettingsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planner.
        /// </summary>
        internal static string Planner {
            get {
                return ResourceManager.GetString("Planner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all required properties have been configured..
        /// </summary>
        internal static string PropNotSet {
            get {
                return ResourceManager.GetString("PropNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string Prvtext {
            get {
                return ResourceManager.GetString("Prvtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display error messages in web part.
        /// </summary>
        internal static string ShowErrorsDesc {
            get {
                return ResourceManager.GetString("ShowErrorsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show errors.
        /// </summary>
        internal static string ShowErrorsName {
            get {
                return ResourceManager.GetString("ShowErrorsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students&apos; site URL.
        /// </summary>
        internal static string StudentSiteURLDesc {
            get {
                return ResourceManager.GetString("StudentSiteURLDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students&apos; site URL.
        /// </summary>
        internal static string StudentSiteURLTitle {
            get {
                return ResourceManager.GetString("StudentSiteURLTitle", resourceCulture);
            }
        }
    }
}
