//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLG2007.Helper.MasterpageSetter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLG2007.Helper.MasterpageSetter.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred and returned with the following message {0}  Please contact your administrator..
        /// </summary>
        internal static string DetailedErrorMessage {
            get {
                return ResourceManager.GetString("DetailedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Settings.
        /// </summary>
        internal static string ExcludedContentTypesCat {
            get {
                return ResourceManager.GetString("ExcludedContentTypesCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holds a comma separated list of content types that are not populated for the user to search in..
        /// </summary>
        internal static string ExcludedContentTypesDesc {
            get {
                return ResourceManager.GetString("ExcludedContentTypesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded Content Types.
        /// </summary>
        internal static string ExcludedContentTypesTitle {
            get {
                return ResourceManager.GetString("ExcludedContentTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the same name already exists.  To overwrite the file check overwrite existing files option..
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully..
        /// </summary>
        internal static string FileUploaded {
            get {
                return ResourceManager.GetString("FileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name contains invalid characters.  Please use a different name.  Common invalid characters include the following: # % &amp; * : &lt; &gt; ? / { | }.
        /// </summary>
        internal static string InvalidCharsInFile {
            get {
                return ResourceManager.GetString("InvalidCharsInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configured document library is invalid.  Please contact the administrator..
        /// </summary>
        internal static string InvalidDocumentLibrary {
            get {
                return ResourceManager.GetString("InvalidDocumentLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file cannot be uploaded.  Please verify that the file path is correct or the file is compressed in a valid zip format..
        /// </summary>
        internal static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata file does not exist in the package.  Please make sure that the package is valid..
        /// </summary>
        internal static string InvalidPackage {
            get {
                return ResourceManager.GetString("InvalidPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The learning resource cannot be uploaded because it exceeds the maximum length allowed by the Web administrator. Please try again with less data..
        /// </summary>
        internal static string MaximumFileSizeReached {
            get {
                return ResourceManager.GetString("MaximumFileSizeReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a content type.
        /// </summary>
        internal static string MultipleContentTypesHeader {
            get {
                return ResourceManager.GetString("MultipleContentTypesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content types attached to the document library..
        /// </summary>
        internal static string NoContentTypesAttached {
            get {
                return ResourceManager.GetString("NoContentTypesAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the necessary permissions for {0} at {1}.  Please request from the site administrator to have add and modify permissions..
        /// </summary>
        internal static string NoPermissions {
            get {
                return ResourceManager.GetString("NoPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing files.
        /// </summary>
        internal static string OverrideExistingFiles {
            get {
                return ResourceManager.GetString("OverrideExistingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all required properties have been configured..
        /// </summary>
        internal static string PropertiesEmpty {
            get {
                return ResourceManager.GetString("PropertiesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Settings.
        /// </summary>
        internal static string ShowErrorsCat {
            get {
                return ResourceManager.GetString("ShowErrorsCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides error details in messages..
        /// </summary>
        internal static string ShowErrorsDesc {
            get {
                return ResourceManager.GetString("ShowErrorsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Errors.
        /// </summary>
        internal static string ShowErrorsTitle {
            get {
                return ResourceManager.GetString("ShowErrorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type available.
        /// </summary>
        internal static string SingleContentTypeHeader {
            get {
                return ResourceManager.GetString("SingleContentTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Settings.
        /// </summary>
        internal static string SourceDocumentLibraryCat {
            get {
                return ResourceManager.GetString("SourceDocumentLibraryCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document library URL with custom content types to search for learning resources .
        /// </summary>
        internal static string SourceDocumentLibraryDesc {
            get {
                return ResourceManager.GetString("SourceDocumentLibraryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Document Library.
        /// </summary>
        internal static string SourceDocumentLibraryTitle {
            get {
                return ResourceManager.GetString("SourceDocumentLibraryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred.  Please contact your administrator..
        /// </summary>
        internal static string StandardErrorMessage {
            get {
                return ResourceManager.GetString("StandardErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Settings.
        /// </summary>
        internal static string XmlFilePathCat {
            get {
                return ResourceManager.GetString("XmlFilePathCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma separated list of the supported metadata XML files.  These files are parsed for property values mapped to site column in the content type.
        /// </summary>
        internal static string XmlFilePathDesc {
            get {
                return ResourceManager.GetString("XmlFilePathDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML File Path.
        /// </summary>
        internal static string XmlFilePathTitle {
            get {
                return ResourceManager.GetString("XmlFilePathTitle", resourceCulture);
            }
        }
    }
}
