//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLG2007.WebParts.MetaSearch {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLG2007.WebParts.MetaSearch.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred and returned with the following message {0}  Please contact your administrator..
        /// </summary>
        internal static string DetailedErrorMessage {
            get {
                return ResourceManager.GetString("DetailedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Learning Actions.
        /// </summary>
        internal static string ELearningActions {
            get {
                return ResourceManager.GetString("ELearningActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results matching your search were found..
        /// </summary>
        internal static string EmptySearchResults {
            get {
                return ResourceManager.GetString("EmptySearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Settings.
        /// </summary>
        internal static string ExcludedContentTypesCat {
            get {
                return ResourceManager.GetString("ExcludedContentTypesCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holds a comma separated list of content types that are not populated for the user to search in..
        /// </summary>
        internal static string ExcludedContentTypesDesc {
            get {
                return ResourceManager.GetString("ExcludedContentTypesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded Content Types.
        /// </summary>
        internal static string ExcludedContentTypesTitle {
            get {
                return ResourceManager.GetString("ExcludedContentTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Settings.
        /// </summary>
        internal static string ExcludedFieldsCat {
            get {
                return ResourceManager.GetString("ExcludedFieldsCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holds a comma separated list of fields that are not populated for the user..
        /// </summary>
        internal static string ExcludedFieldsDesc {
            get {
                return ResourceManager.GetString("ExcludedFieldsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded Fields.
        /// </summary>
        internal static string ExcludedFieldsTitle {
            get {
                return ResourceManager.GetString("ExcludedFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string Integer {
            get {
                return ResourceManager.GetString("Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configured document library is invalid.  Please contact the administrator..
        /// </summary>
        internal static string InvalidDocumentLibrary {
            get {
                return ResourceManager.GetString("InvalidDocumentLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a content type.
        /// </summary>
        internal static string MultipleContentTypesHeader {
            get {
                return ResourceManager.GetString("MultipleContentTypesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content types attached to the document library..
        /// </summary>
        internal static string NoContentTypesAttached {
            get {
                return ResourceManager.GetString("NoContentTypesAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the necessary permissions for {0} at {1}.  Please request from the site administrator to have at least view permissions..
        /// </summary>
        internal static string NoPermissions {
            get {
                return ResourceManager.GetString("NoPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter one or more search words..
        /// </summary>
        internal static string NoSearchWords {
            get {
                return ResourceManager.GetString("NoSearchWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Settings.
        /// </summary>
        internal static string NumberofResultsCat {
            get {
                return ResourceManager.GetString("NumberofResultsCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of search result items per page to view in search results. .
        /// </summary>
        internal static string NumberofResultsDesc {
            get {
                return ResourceManager.GetString("NumberofResultsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Items in Results.
        /// </summary>
        internal static string NumberofResultsTitle {
            get {
                return ResourceManager.GetString("NumberofResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all required properties have been configured..
        /// </summary>
        internal static string PropertiesEmpty {
            get {
                return ResourceManager.GetString("PropertiesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Settings.
        /// </summary>
        internal static string ShowErrorsCat {
            get {
                return ResourceManager.GetString("ShowErrorsCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides error details in messages..
        /// </summary>
        internal static string ShowErrorsDesc {
            get {
                return ResourceManager.GetString("ShowErrorsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Errors.
        /// </summary>
        internal static string ShowErrorsTitle {
            get {
                return ResourceManager.GetString("ShowErrorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type available.
        /// </summary>
        internal static string SingleContentTypeHeader {
            get {
                return ResourceManager.GetString("SingleContentTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Settings.
        /// </summary>
        internal static string SourceDocumentLibraryCat {
            get {
                return ResourceManager.GetString("SourceDocumentLibraryCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document library URL with custom content types to search for learning resources .
        /// </summary>
        internal static string SourceDocumentLibraryDesc {
            get {
                return ResourceManager.GetString("SourceDocumentLibraryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Document Library.
        /// </summary>
        internal static string SourceDocumentLibraryTitle {
            get {
                return ResourceManager.GetString("SourceDocumentLibraryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred.  Please contact your administrator..
        /// </summary>
        internal static string StandardErrorMessage {
            get {
                return ResourceManager.GetString("StandardErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered invalid data in {0}.  {1} values are only allowed in {0}..
        /// </summary>
        internal static string TypeValidationError {
            get {
                return ResourceManager.GetString("TypeValidationError", resourceCulture);
            }
        }
    }
}
